sudo: false
language: node_js
node_js:
- stable
- '8'
script:
- npm install
- npm test
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: dev.api@mynidays.com
  api_key:
    secure: rSSF1KuOJpZeGhAGZnTL3UZ/ezUOCfeUOBjkN7pI2FL1SEnaW6ZZ68ijlr5diUf8vSs8XnNOg8g9t2vHZCrgrjPPkM/8S8rDhxfhjBw1EF7BbOXcKOS9V0KuAMWqaQgAib1wgRwbJTvoCiRVaneh8hiVQLpI3xR4C21iBGwWMKmeNIPBNE9ykN9NJIW/uaomQL3AAYxdjm4Lx5viGUkqwRmkSVjAceGL1rzps+8Fk8V2vXpzEPTSrPT7KXgd/OnUvKrVhLS3T/hnJInqxTfNZD1fp/d5c3xfsJlCf41sLB3ycN7V8ARr0KKiDSvBWRsc2E1tIwF6KwmcP+CkwLygm5yn7yEcL6wmSXbiZsTASS4/s+tPxRWacAO3wXVtrmQKXOmyrWSvgiCblUhBa7wkG1b+PuKBLS8b2VtQCqgQN/RcgHHMqFeczQPK3LV3lEceEr1kD2eJ9NhqE9n3tjbUC0ykwIeyXyCCpBd7+UmvQaYBRN90Fz/YgfX63Q0cjecgxV7K6ZeScD7DBuPS3HpsyDHVE7kep6lbW7bydwbN5j1HQaWHv7naL3jZT5/jx8UphQKOB+rVq57zBYgCIOcWUgxcMVpTTmLOlFTGTYZjoyekepv2XDJJrasXMl4q6Tv2yDfuB/XJ3lf40Qh8APz/NsfrM/0Oj/uGRu8dk7NeC9U=
  on:
    branch: master
    node: stable
notifications:
  slack:
    secure: UeW0SiVVa4iJLk+1xkxJtls8PJQpUn9Yhxo6Oo2/MzmKtt3f6tjI2JusCXrCVtUihlkUiCIQxlmQPClvNGU3RCcy7b/zwARPsALvaahSGuTcRSRRjohgoNKgTv64POqpDnR2H/75dkC+SwDBjyGtOIYUvu9ee/3DkOuHgp1GFEbY/oOvU/6eGvugUKgheP1SuJ6brRI7lKjgxR5sDb2fnLbYGTJHYAr2tGzyZpIMK4FzYY7WHkPyTf0n9pEn9vVLNJTWa/5/85DTPWYpDcnSRfq6A875I969554sLu8H77q55CHkWwY5763R1tfDTYySq9TPDWDQQnrdO5JNoowKcL9PE4kqbMzfo/voodasMSUvwZRPzfI9SWsX+eiNzd7gz3OHilzIAbo0i9cS4cWRx/yD/o9oiT9nN32lsFgReLRo44Q9WnoZi81eYUIEzTqdAHVttZvAyhzoTgD8PFrIAWsfydqdXOZR3y1GpvXiRWShaboRyO3XZdDdcn1U8AYPZrvGuGZMy9m5TBuBi6mdGDmbTbo2TNvxm+eK+WCd5MdzaMBR60jBqpqTbBd90xFsHn5F3cslkMON6Li5JJS+XPIMTNBbApZqWqT8tPxKzx4ggzQPGH8DfB1gIHE9ejlvdmFZ4mOfDzan+vAfn33uI3ECU4zl7Z1xmzDY3mwuN3o=
    on_success: never
    on_failure: always